Feat/creation user
develhope/Java27-progetto3-team1 pull request #14
Opened 2024-10-05 07:40 UTC by SimoCu3

init "User creation system"

Add class: 
UserController
UserService
CreateUserDTO

Add metod:
createUser in UserController
createUser in UserService
fromCreateUserDTOToUser in UserMapper

Resolve issue #3

2024-10-05 11:20 UTC, FedericaSilver commented on src/main/java/com/team1/dealerApp/entities/User.java
> +	@OneToMany
Questa annotazione già definisce la relazione nel db?

2024-10-05 11:20 UTC, FedericaSilver commented on src/main/java/com/team1/dealerApp/services/UserService.java
> +            throw new Exception("Either Email or Password is null");
Forse invece di un'eccezione generica potresti usare BadRequest?

2024-10-06 07:26 UTC, luigimonteforte5 requested changes

2024-10-06 07:26 UTC, luigimonteforte5 commented on src/main/java/com/team1/dealerApp/services/UserService.java
> +    }
Dovresti introdurre altri metodi per avere un crudo completo, quindi rimozione, modifica e lettura

2024-10-08 09:25 UTC, luigimonteforte5 approved these changes
Ok, sono presenti tutti i metodi per un crud base

2024-10-08 09:29 UTC, SimoCu3 commented
1.
init "User creation system"
Add class:
UserController
UserService
CreateUserDTO

Add metod:
createUser in UserController
createUser in UserService
fromCreateUserDTOToUser in UserMapper

2.
Fix "Feat/creation User"
Add metod setId in class User

fix UserDTO, CreateUserDTO

3.
Feat/creation User
Add:

getUserById in UserController
updateUser in UserController
deleteUser in UserController

getUserById in UserService
updateUser in UserService
deleteUser in UserService

Resolve issue https://github.com/develhope/Java27-progetto3-team1/issues/3

2024-10-08 09:43 UTC, merged