Feat/test movie service
develhope/Java27-progetto3-team1 pull request #39
Opened 2024-10-09 17:29 UTC by FedericaSilver

resolve issue #32

2024-10-10 13:15 UTC, aegroto requested changes
i test sommariamente vanno bene, ci sono però alcune cose che ho segnalato e che vanno corrette. alcune imperfezioni sono state ripetute anche negli ultimi test, per cui correggile anche li.

2024-10-10 13:15 UTC, aegroto commented on src/test/java/com/team1/dealerApp/video/movie/MovieServiceTest.java
> +    MovieDTO movieDTO;
sempre meglio specificare la visibilità delle variabili, anche nei test

inoltre i nomi movieDTO, movieDTO2 ecc... non vanno bene, bisogna dare sempre nomi significativi alle variabili e non numerarle in questo modo.

2024-10-10 13:15 UTC, aegroto commented on src/test/java/com/team1/dealerApp/video/movie/MovieServiceTest.java
> +        movieDTO = new MovieDTO("Il signore degli anelli: il ritorno del Re", 110, Genre.FANTASY, castMovie, "Peter Jackson", Year.of(2003), 30.00, 10.00, "Il ritorno del Re", 4.0f, VideoStatus.PURCH
in questo caso, movieDTO potrebbe chiamarsi "purchasableMovieDTO" e movieDTO2 "rentableMovieDTO", poichè la differenza credo sia solo quella. l'importante è capire quando un oggetto va utilizzato nei test.

2024-10-10 13:15 UTC, aegroto commented on src/test/java/com/team1/dealerApp/video/movie/MovieServiceTest.java
> +        movie = new Movie("Il signore degli anelli: il ritorno del Re", Genre.FANTASY, castMovie, "Peter Jackson", Year.of(2003), 30.00, 10.00, "Il ritorno del Re", 4.0f, VideoStatus.PURCHASABLE, 110
volendo questi oggetti si potrebbero creare tramite il mapper, per essere sicuri che corrispondano a ciò che verrebbe fuori dal DTO e viceversa. in alternativa rimuovi proprio queste variabili d'istanza e creare l'oggetto dal DTO nei test quando serve, o viceversa.

2024-10-10 13:15 UTC, aegroto commented on src/test/java/com/team1/dealerApp/video/movie/MovieServiceTest.java
> +        verify(movieRepository, times(1)).save(any(Movie.class));
ci sono troppi assert in questo test, idealmente ogni test dovrebbe avere un solo assert.

2024-10-10 13:15 UTC, aegroto commented on src/test/java/com/team1/dealerApp/video/movie/MovieServiceTest.java
> +        verify(movieRepository, times(1)).save(any(Movie.class));
In questo caso specifico secondo me l'unico assert che ha senso è quello a linea 73. l'assert a linea 70 è sottinteso, se result è null l'equals sarà falso. quello a linea 76 verifica che il metodo del repository viene chiamato, ma questo dipende dal funzionamento interno della classe che a te non interessa. a te importa che il risultato ritornato dal metodo sia corretto.

2024-10-10 13:15 UTC, aegroto commented on src/test/java/com/team1/dealerApp/video/movie/MovieServiceTest.java
> +    public void testAddMovie_MovieAlreadyExists() {
sarebbe meglio chiamarlo "_whenMovieAlreadyExists"

2024-10-10 13:15 UTC, aegroto commented on src/test/java/com/team1/dealerApp/video/movie/MovieServiceTest.java
> +        verify(movieRepository, never()).save(any(Movie.class));
anche qui, idealmente un test deve verificare una sola cosa. analizza tutti i test e cerca di ridurre il numero di assert.

2024-10-11 09:17 UTC, aegroto approved these changes

2024-10-11 09:32 UTC, luigimonteforte5 reviewed
Ho lascato un commento sulla classe dei test, decidi tu se integrarlo o meno

2024-10-11 09:32 UTC, luigimonteforte5 commented on src/test/java/com/team1/dealerApp/video/movie/MovieServiceTest.java
> +    private final MovieMapper movieMapper = new MovieMapper();
Potresti mettere movie mapper in cima dato che si tratta di un'istanza e lasciare tutti i mock uniti tra loro

2024-10-11 09:34 UTC, merged