Feat/rental
develhope/Java27-progetto3-team1 pull request #47
Opened 2024-10-11 10:03 UTC by FedericaSilver

resolve issue #19

2024-10-11 14:02 UTC, luigimonteforte5 requested changes
Ho richiesto dei cambiamenti nelle annotation, controlla i commenti per saperne di più

2024-10-11 14:03 UTC, luigimonteforte5 requested changes

2024-10-11 14:03 UTC, luigimonteforte5 commented on src/main/java/com/team1/dealerApp/user/User.java
> +	@OneToMany
Sarebbe meglio mettere aggiungere l'annotation @JoinColumn per rendere più chiara la relazione

2024-10-11 14:38 UTC, luigimonteforte5 approved these changes

2024-10-14 09:12 UTC, SimoCu3 approved these changes
Approvo, puoi mergiare

2024-10-14 09:27 UTC, merged