Feat/Purchase
develhope/Java27-progetto3-team1 pull request #50
Opened 2024-10-14 23:13 UTC by SimoCu3

Add

Class Purchase
Enum OrderStatus
Interface PurchaseRepository

Resolve issue #20

2024-10-15 13:52 UTC, luigimonteforte5 requested changes

2024-10-15 13:52 UTC, luigimonteforte5 commented on src/main/java/com/team1/dealerApp/purchase/OrderStatus.java
> +    //PAID,  (Forse non necessaria una volta pagato)
Paid dovrebbe essere necessario per memorizzare ordini già pagati nello storico di un cliente

2024-10-15 13:52 UTC, luigimonteforte5 commented on src/main/java/com/team1/dealerApp/purchase/Purchase.java
> +    private boolean paid;
Dato che hai l'enum converrebbe inserire il paid come status al suo interno e rimuovere il flag

2024-10-15 14:02 UTC, FedericaSilver commented on src/main/java/com/team1/dealerApp/purchase/Purchase.java
> +    private SubscriptionStatus subscriptionStatus;
Come mai nella classe Acquisto abbiamo come attributo l'abbonamento?

2024-10-16 12:27 UTC, luigimonteforte5 approved these changes

2024-10-16 13:48 UTC, merged