Added Admin Entity
develhope/Java27-progetto3-team1 pull request #54
Opened 2024-10-16 09:07 UTC by SaraPerri

2024-10-16 09:21 UTC, FedericaSilver requested changes

2024-10-16 09:21 UTC, FedericaSilver commented on src/main/java/com/team1/dealerApp/admin/AdminService.java
> +    public AdminDTO createAdmin(CreateAdminDTO createAdminDTO) throws Exception {
Qui andrebbe sempre BadRequestException visto che è quella gestita dal metodo

2024-10-16 09:21 UTC, FedericaSilver commented on src/main/java/com/team1/dealerApp/admin/AdminService.java
> +    public AdminDTO updateAdmin(UUID id, CreateAdminDTO createAdminDTO) throws Exception {
Anche qui è da cambiare nella firma non va thorws Exception, forse l'eccezione più corretta sarebbe NoSuchElement

2024-10-16 09:21 UTC, FedericaSilver commented on src/main/java/com/team1/dealerApp/admin/Admin.java
> +        @Column(nullable = false)
Forse l'email sarebbe meglio averla come Unique per non permettere registrazioni con la stessa email

2024-10-16 09:23 UTC, luigimonteforte5 requested changes

2024-10-16 14:14 UTC, FedericaSilver commented on src/main/java/com/team1/dealerApp/admin/Admin.java
> +public class Admin {
Manca l'annotation @Entity

2024-10-17 13:47 UTC, luigimonteforte5 approved these changes

2024-10-17 13:50 UTC, FedericaSilver approved these changes

2024-10-17 13:53 UTC, merged