Feat/Purchase
develhope/Java27-progetto3-team1 pull request #56
Opened 2024-10-17 07:43 UTC by SimoCu3

Add:
double purchasePrice in Class Purchase,
Page<Purchase> findByPurchaseUserId in Class PurchaseRepository.

Create Class with their own methods:
PurchaseDTO,
CreatePurchaseDTO,
PurchaseController,
PurchaseService,
PurchaseMapper.

Resolve issue #22

2024-10-17 14:19 UTC, FedericaSilver commented on src/main/java/com/team1/dealerApp/purchase/PurchaseMapper.java
> +    public PurchaseDTO toPurchaseDTO(Purchase purchase){
Potremmo semplificare la nomenclatura dei metodi invece di toPurchaseDTO potrebbe essere semplicemente toDTO

2024-10-17 14:19 UTC, FedericaSilver commented on src/main/java/com/team1/dealerApp/purchase/PurchaseService.java
> +    public void deletePurchaseById(Long id) {
Visto che negli altri Service nel metodo delete come tipo di ritorno abbiamo il boolean modificherei anche qui così da avere più coerenza nel codice

2024-10-18 09:17 UTC, luigimonteforte5 commented on src/main/java/com/team1/dealerApp/purchase/PurchaseRepository.java
> +    Page<Purchase> findByPurchaseUserId(UUID userId, Pageable pageable);
Questo metodo dovrebbe essere già presente di default in JPA Respository

2024-10-18 09:17 UTC, luigimonteforte5 commented on src/main/java/com/team1/dealerApp/purchase/PurchaseService.java
> +            throw new NoSuchElementException("Purchase's list is empty");
Come messaggio per l'eccezione potrebbe andare meglio "User with id " + userId + " has no purchases"

2024-10-18 09:17 UTC, luigimonteforte5 requested changes

2024-10-18 09:17 UTC, luigimonteforte5 commented on src/main/java/com/team1/dealerApp/purchase/PurchaseService.java
> +        purchaseSelected.setId(id);
Il SetId andrebbe fatto prima di salvare l'oggetto a repository

2024-10-18 13:27 UTC, luigimonteforte5 approved these changes

2024-10-18 13:49 UTC, merged