Feat/Subscription
develhope/Java27-progetto3-team1 pull request #90
Opened 2024-10-31 10:28 UTC by SimoCu3

Add Entity Subscription

Just some fix ; in User

2024-10-31 10:32 UTC, FedericaSilver requested changes

2024-10-31 10:32 UTC, FedericaSilver commented on src/main/java/com/team1/dealerApp/subscription/Subscription.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE)
GenerationType.IDENTITY e non sequence

2024-10-31 10:32 UTC, FedericaSilver commented on src/main/java/com/team1/dealerApp/subscription/Subscription.java
> +    @Column(name = "price", nullable = false)
Non serve specificare il nome se è uguale, tieni solo il nullable.

2024-10-31 10:40 UTC, FedericaSilver commented on src/main/java/com/team1/dealerApp/subscription/Subscription.java
> +    @Column(name = "status")
Anche qui non serve il name

2024-10-31 10:41 UTC, luigimonteforte5 requested changes
Sarebbe anche il caso di aggiungere una repository e un DTO, oltre che l'altro lato della relazione all'interno di User per rendere la entity completa

2024-10-31 10:41 UTC, luigimonteforte5 commented on src/main/java/com/team1/dealerApp/subscription/Subscription.java
> +    @ManyToOne
La relazione dovrebbe essere una many to many: uno user può avere più abbonamenti, e un abbonamento può avere più user associati.

2024-10-31 10:41 UTC, luigimonteforte5 commented on src/main/java/com/team1/dealerApp/subscription/Subscription.java
> +    @Column(name = "status")
Anche qui, non ha senso mettere name = status, la colonna si chiamerà come il parametro

2024-10-31 10:50 UTC, luigimonteforte5 requested changes

2024-10-31 10:50 UTC, luigimonteforte5 commented on src/main/java/com/team1/dealerApp/subscription/Subscription.java
> +    private LocalDate endDate;
Qui @Column invece andrebbe messo per separare end_date

2024-10-31 10:52 UTC, FedericaSilver requested changes
Mancano Repository e DTO

2024-11-03 11:58 UTC, FedericaSilver approved these changes

2024-11-03 14:39 UTC, luigimonteforte5 approved these changes

2024-11-04 08:14 UTC, merged